### ISSUE TITLE
Polish Console App

### ISSUE THREAD

**Issue by ryanjduffy** [enactjs/agate-apps#19]
Breakdown of work in prep for demo

## Tier 1
* [x] Remove "Hello World" View  - @sugardave 
* [x] Add Auto Icon set enactjs/agate#36 - @teckliew 
  * maybe use https://icomoon.io/
  * ryan to send carbon icons to Teck
* [x] Merge ToggleButton enactjs/agate#25 - @germboy 
* [x] Merge Picker enactjs/agate#6 - @germboy 
* [x] Merge Input enactjs/agate#20 - @ryanjduffy
* [x] Create App Template in enactjs/templates (enactjs/agate#23) - @rundmt 

## Tier 2
* [x] Date/Time Popup with Pickers (#17) - @rundmt 
* [x] Horizontal Contact Scroller on Phone Screen (#18) - @haileyR 
* [x] Add Ongoing Call Dialog (#24) - @sugardave
